// vendor_modules
import 'bootstrap';
import 'bootstrapSwitch';
import 'dateRangePicker';
import 'pagination';
import 'select2';
// node_modules
import 'jquery';
import 'accounting';
import 'backbone';
import 'marionette';
import 'radio';
import 'bluebird';
import 'dropzone';
import 'highcharts';
import 'lodash';
import 'moment';
import 'store';
// kendo
import 'kendo.core';
import 'kendo.grid';
import 'kendo.multiselect';
import 'kendo.numerictextbox';
import 'kendo.virtuallist';