// css
import 'css/bootstrap.css';
import 'css/bootstrap-theme.css';
import 'css/bootstrap-switch.css';
import 'css/daterangepicker.css';
import 'css/select2.css';
import 'css/select2-bootstrap.css';
import 'css/basic.css';
import 'css/dropzone.css';
import 'css/kendo/kendo.common-bootstrap.min.css';
import 'css/kendo/kendo.bootstrap.min.css';
// vendor_modules
import 'bootstrap';
import 'bootstrapSwitch';
import 'dateRangePicker';
import 'pagination';
import 'select2';
// node_modules
import 'jquery';
import 'accounting';
import 'backbone';
import 'marionette';
import 'radio';
import 'bluebird';
import 'dropzone';
import 'highcharts';
import 'lodash';
import 'moment';
import 'store';
// kendo
import 'kendo.core';
import 'kendo.grid';
import 'kendo.multiselect';
import 'kendo.numerictextbox';
import 'kendo.virtuallist';
